### ISSUE TITLE
GUI server ups

### ISSUE THREAD

**Issue by PHIDIAS0303** [explosivegaming/ExpCluster#337]
Error while running event level::on_player_display_resolution_changed (ID 107)
__level__/modules/exp_legacy/modules/gui/server-ups.lua:64: attempt to index local 'label' (a nil value)
stack traceback:
    __level__/modules/exp_legacy/modules/gui/server-ups.lua:64: in function 'handler'
    __level__/modules/exp_legacy/utils/event.lua:22: in function 'handler'
    __core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**Comment by Cooldude2606** [comment]
This is a known issue when patching a save with the scenario after players have already joined. We will need a cleaner way to deal with `on_player_created` (this is when the label is made)

**Comment by Cooldude2606** [comment]
Fixed by [commit](https://github.com/explosivegaming/ExpCluster/commit/114c9e4153e41ae823945936241f4847844271f6).
